### PR TITLE
Fix isssue of creation of multiple vultr instance due to eventual consistency

### LINKED ISSUE #1704: Vultr: Multiple Instances for Single Machine
## Problem
My team uses an older fork of the Vultr cloud provider, and we've now seen an issue on more than one occasion where Vultr tag state gets duplicated. What we tend to see is two Vultr instances, both with a tag for the same Machine UID.

Our best guess is that tags are only eventually consistent in Vultr, and it is possible for reconciliation to result in rare cases where two Vultr instances are tagged for the same machine. This predictably causes a variety of issues.

We are looking at potentially working on a PR to resolve this scenario, but wanted to verify our approach, so would love any feedback on this issue!

## Planned Approach
Since Vultr returns a unique ID on every create call, we were looking to do something like the `anexia` provider, where rather than relying on the tag in vultr, the provider attaches the Vultr UID into the `ProviderStatus` payload and favors that. The tag would still be set in Vultr (which helps with diagnostics) and could still be used as a fallback, which makes for clean migration to the new tracking model over time.

There are some other advantages to this approach, such as making it easier to find the instance Vultr when a `Get` is performed.

### PR DESCRIPTION
**Pull request by 2000yeshu**
**What this PR does / why we need it**:
There has been a bug introduced because of vultr wherein the tags on instances are eventually consistent due to which machine controller is led to believe that the instance was not created as we poll instance based on label and tags. This PR wait for complete creation of the instance so that eventual fetches to get machine are more deterministic
Additionally, there is the support for Vultr bare metal instances
And suppport for specifying VPC v1/v2 for instances has been added in accordance to https://www.vultr.com/api/#tag/instances/operation/create-instance and https://www.vultr.com/api/#tag/baremetal/operation/create-baremetal

**Which issue(s) this PR fixes**:

Fixes #1704

**What type of PR is this?**

/kind bug
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
- Fixed multiple instance creation issue for vultr by waiting for instance to get started.
- Add support for vultr bare metal instances
- Upgrade govulr to v3
- Add support for vultr VPC v1/v2
- Handle go vultr API response codes 
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
/ok-to-test

@2000yeshu FYI, the "documentation" block is only meant to provide a link to a https://github.com/kubermatic/docs PR. Looks like what you added should be in the "release notes" block, right above that.

**Comment by 2000yeshu** [comment]
Ah, fixed it.

File: pkg/cloudprovider/provider/vultr/provider.go [hunk 1]
```diff
@@ -126,6 +154,55 @@ func (p *provider) AddDefaults(_ *zap.SugaredLogger, spec clusterv1alpha1.Machin
...
+	accountvpcs := []string{}
+	var requestedvpcs []string
+
+	if legacyVPC {
+		for {
+			vpcs, meta, resp, err := client.VPC.List(ctx, &govultr.ListOptions{})
+			if err != nil {
+				return validVpc, vltErrorToTerminalError(resp.StatusCode, err)
+			}
+			defer resp.Body.Close()
```
Comment (lanwen) [inline pkg/cloudprovider/provider/vultr/provider.go:168]: If I may raise a concern here: usage of `defer` in a loop could have unpredictable side effects, as doesn't close anything until the end of the loop. 

More info: https://blog.learngoprogramming.com/gotchas-of-defer-in-go-1-8d070894cb01

It might be beneficial to do something like this to be on the safe side (with the correct types):

```go
                     vpcs, meta, err := func(ctx, client) (any, any, error) {
				vpcs, meta, resp, err := client.VPC.List(ctx, &govultr.ListOptions{})
				if err != nil {
					return nil, nil, vltErrorToTerminalError(resp.StatusCode, err)
				}
				defer resp.Body.Close()
				
				return vpcs, meta
			}(ctx, client)
```

(could be other variations moving more into function, like continuation condition)

File: pkg/cloudprovider/provider/vultr/provider.go [hunk 2]
```diff
@@ -168,52 +245,168 @@ func (p *provider) Validate(ctx context.Context, _ *zap.SugaredLogger, spec clus
...
+		UserData: base64.StdEncoding.EncodeToString([]byte(userdata)),
+		Tags:     tags,
+
+		EnableIPv6: &c.EnableIPv6,
+		EnableVPC:  &c.EnableVPC,
+		AttachVPC:  c.VpcID,
+		EnableVPC2: &c.EnableVPC2,
+		AttachVPC2: c.Vpc2Id,
+	}
+	instance, resp, err := client.Instance.Create(ctx, &instanceCreateRequest)
```
Comment (lanwen) [inline pkg/cloudprovider/provider/vultr/provider.go:379]: I might be unfamiliar with vultr API, so it might be a completely silly question, however, shouldn't be response body closed here, as I noticed you do that in some other cases?

File: pkg/cloudprovider/provider/vultr/provider.go (hunk 1 above)
Comment (2000yeshu) [reply pkg/cloudprovider/provider/vultr/provider.go]: Ah, good catch. Fixed it.

File: pkg/cloudprovider/provider/vultr/provider.go (hunk 2 above)
Comment (2000yeshu) [reply pkg/cloudprovider/provider/vultr/provider.go:394]: You are right, it should be closed. They are not closing it in the underlying function

Comment (2000yeshu) [reply pkg/cloudprovider/provider/vultr/provider.go:394]: Fixed it.

File: pkg/cloudprovider/provider/vultr/types/types.go [hunk 3]
```diff
@@ -22,11 +22,17 @@ import (
...
-	OsID   providerconfigtypes.ConfigVarString `json:"osId"`
-	Tags   []string                            `json:"tags,omitempty"`
+	PhysicalMachine bool                                `json:"physicalMachine,omitempty"`
+	APIKey          providerconfigtypes.ConfigVarString `json:"apiKey,omitempty"`
+	Region          providerconfigtypes.ConfigVarString `json:"region"`
+	Plan            providerconfigtypes.ConfigVarString `json:"plan"`
+	OsID            providerconfigtypes.ConfigVarString `json:"osId"`
+	Tags            []string                            `json:"tags,omitempty"`
+	VpcID           []string                            `json:"vpcId,omitempty"`
+	Vpc2Id          []string                            `json:"vpc2Id,omitempty"`
```
Comment (lanwen) [inline pkg/cloudprovider/provider/vultr/types/types.go:32]:
```suggestion
	Vpc2ID          []string                            `json:"vpc2Id,omitempty"`
```
Just to make sure it wasn't a miss - you seem to follow the uppercase notation for `ID` everywhere, but not in this case, is that intentional?

File: pkg/cloudprovider/provider/vultr/provider.go [hunk 4]
```diff
@@ -50,11 +65,17 @@ func New(configVarResolver *providerconfig.ConfigVarResolver) cloudprovidertypes
...
+	APIKey          string
+	Region          string
+	Plan            string
+	OsID            string
+	Tags            []string
+	VpcID           []string
+	EnableVPC       bool
+	EnableIPv6      bool
+	EnableVPC2      bool
+	Vpc2Id          []string
```
Comment (lanwen) [inline pkg/cloudprovider/provider/vultr/provider.go:78]:
```suggestion
	Vpc2ID          []string
```

To make sure it was an intentional difference with other cases where `ID` used uppercase. Would it make sense to follow here the same style?

File: pkg/cloudprovider/provider/vultr/types/types.go (hunk 3 above)
Comment (2000yeshu) [reply pkg/cloudprovider/provider/vultr/types/types.go:32]: No actually i prefer snakecase but the lint was failing due to that. So I made this partial change. Will make it consistent.

File: pkg/cloudprovider/provider/vultr/provider.go [hunk 5]
```diff
@@ -155,64 +245,188 @@ func (p *provider) Validate(ctx context.Context, _ *zap.SugaredLogger, spec clus
...
+func (p *provider) waitForInstanceCreation(ctx context.Context, c *Config, instance instance.Instance, machine *clusterv1alpha1.Machine) error {
+	return wait.PollUntilContextTimeout(ctx, createCheckPeriod, createCheckTimeout, false, func(ctx context.Context) (bool, error) {
+		var err error
+		if !c.PhysicalMachine {
+			_, err = p.getVirtualMachine(ctx, c, machine)
+		} else {
+			_, err = p.getPhysicalMachine(ctx, c, machine)
+		}
+
+		if err != nil && err != cloudprovidererrors.ErrInstanceNotFound {
```
Comment (realjenius) [inline pkg/cloudprovider/provider/vultr/provider.go:363]: When testing this latest push I saw that it skips this entire conditional, then returns true, but then the instance can't be found during reconciliation and it creates another.

I think the `err != cloudprovidererrors.ErrInstanceNotFound` prevents it from going into this retry loop correctly. It's basically the same check as `if cloudprovidererrors.IsNotFound(err)`. I removed the `err != cloudprovidererrors.ErrInstanceNotFound` in my local testbench and it looks to have created a single instance and waited correctly.

File: pkg/cloudprovider/provider/vultr/provider.go [hunk 6]
```diff
@@ -155,64 +245,188 @@ func (p *provider) Validate(ctx context.Context, _ *zap.SugaredLogger, spec clus
...
+				// just that our instance was not found
+				return false, nil
+			}
+			if isTerminalErr, _, _ := cloudprovidererrors.IsTerminalError(err); isTerminalErr {
+				return true, err
+			}
+			// Wait for some time as instance creation is successful
+			// just that we are not able to fetch it
+			time.Sleep(createCheckFailedWaitPeriod)
+			return false, fmt.Errorf("instance %q created but controller failed to fetch instance details", instance.Name())
```
Comment (realjenius) [inline pkg/cloudprovider/provider/vultr/provider.go:375]: I think if you return an error, the poll loop stops and returns the error - I don't think that's the intention here; it might be better to log the error and return nil instead so it keeps retrying.

Comment (2000yeshu) [reply pkg/cloudprovider/provider/vultr/provider.go:375]: As this error is returned when there is a problem with the vultr client itself and the List() request fails inside getPhysicalMachine() or getVirtualMachine().
I feel that that kind of error should not be ignored and loop should be broken returning the reason as to why the client returned an error. It could happen that if vultr server is down or the client is misconfigured, this wait function might never return. What do you think?

File: pkg/cloudprovider/provider/vultr/provider.go (hunk 5 above)
Comment (2000yeshu) [reply pkg/cloudprovider/provider/vultr/provider.go]: Fixed.

File: pkg/cloudprovider/provider/vultr/provider.go (hunk 6 above)
Comment (realjenius) [reply pkg/cloudprovider/provider/vultr/provider.go:375]: Yeah, I suppose it could go either way. There is still a possibility that Vultr is temporarily unreachabler due to some API issue (gateway failure, rate limiting, scheduled maintenance) and we could still get into a duplicate instance scenario.

I think the wait function still has a hard timeout of 5 minutes, right? So I think it'd probably eventually bail out either way. Maybe 5 minutes is a bit excessive in this scenario; but at the same time, if the provider gets this far, then the instance create call completed without error, so at least in theory things are most likely out of sync if the code bails out.

I'm less worried about this particular flow, however, as it's definitely an edge case.

I saw some of the other providers go into a "Cleanup" cycle if they fail creation - is that something that would be a better option here? It might leave an orphaned instance in Vultr, but it wouldn't result in a "two instance" reconciliation problem as the machine for that label would be gone, right?

**Review by realjenius — APPROVED** [review]

File: pkg/cloudprovider/provider/vultr/provider.go (hunk 6 above)
Comment (2000yeshu) [reply pkg/cloudprovider/provider/vultr/provider.go:375]: Cleanup cycle when the Instance creation itself fails or the waiting for label fails?
In any case, what kind of metadata will we give the vultr API to delete instance? 
Tags might not have applied to the instance and can't give the label as the controller might have created another instance for the machine.

**Comment by embik** [comment]
Hey @2000yeshu, you'll need to address the [lint job failing](https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_machine-controller/1706/pull-machine-controller-lint/1704558461922054144):

```
pkg/cloudprovider/provider/vultr/provider.go:365:47: `succesfully` is a misspelling of `successfully` (misspell)
				// Continue the loop as the instances was succesfully fetched
				                                          ^
```

For the other e2e jobs I'm not sure what is going on, we will need to take a look from our side.

File: pkg/cloudprovider/provider/vultr/provider.go (hunk 6 above)
Comment (2000yeshu) [reply pkg/cloudprovider/provider/vultr/provider.go:375]: An ideal way i could think of is to know whether machine-controller controlled label exists on the machine or not. Currently we can't know whether the UID label is present on machine or not. If we could know that, we can add "wait"s wherever (instance.label == machine.name && UID label DNE) either when creating instance or when getting the instance. If we can't, we(provider) gives error.
As for the cleanup i feel that, maybe we can do it syncronously after the "wait"s and delete the instance if the wait ended with no error and no success. But that would need controller changes.

I think the cleanup could be done here as well, after the wait, let me try that.

Comment (2000yeshu) [reply pkg/cloudprovider/provider/vultr/provider.go:375]: Pushed.

**Comment by 2000yeshu** [comment]
> Hey @2000yeshu, you'll need to address the [lint job failing](https://public-prow.loodse.com/view/gs/prow-dev-public-data/pr-logs/pull/kubermatic_machine-controller/1706/pull-machine-controller-lint/1704558461922054144):
> 
> ```
> pkg/cloudprovider/provider/vultr/provider.go:365:47: `succesfully` is a misspelling of `successfully` (misspell)
> 				// Continue the loop as the instances was succesfully fetched
> 				                                          ^
> ```
> 
> For the other e2e jobs I'm not sure what is going on, we will need to take a look from our side.

Done

**Comment by embik** [comment]
/retest

Looking at test history, those tests just randomly flake. Let's hope 1-2 retests bring them in.

**Comment by 2000yeshu** [comment]
I saw that they are failing because of "machinedeployment not found". Maybe ignore the `kubectl delete` stderr?

**Comment by embik** [comment]
> I saw that they are failing because of "machinedeployment not found". Maybe ignore the `kubectl delete` stderr?

I believe that the actual error is hidden somewhere. It doesn't even try to create MachineDeployments, so the test fails pretty early on. But this is not related to your PR at all, we need to do some digging on our side why it's so flaky.

**Review by embik — APPROVED** [review]
/approve

Thank you for contributing to machine-controller's community providers!
