### PR TITLE
fix kubevirt secondary disk naming

### LINKED ISSUE #1378: KubeVirt: Conflict with Secondary Disk naming
Secondary Disk for kubevirt VM has a naming pattern like `secondarydisk0`, `secondarydisk1`.
After scaling the Machine deployment, all the VMs will try to create secondary disks with the same naming pattern resulting in a conflict and some VMs doesn't work.

### PR DESCRIPTION
**Pull request by sankalp-r**
**What this PR does / why we need it**:
This PR adds 'machine-name' prefix to secondary disk's name for kubevirt provider to avoid naming conflict.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #1378 

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
NONE
```

Signed-off-by: Sankalp Rangare <sankalprangare786@gmail.com>

### CODE REVIEW

File: pkg/cloudprovider/provider/kubevirt/provider.go [hunk 1]
```diff
@@ -535,8 +534,8 @@ func (p *provider) Create(ctx context.Context, machine *clusterv1alpha1.Machine,
 
 	// we need this check until this issue is resolved:
 	// https://github.com/kubevirt/containerized-data-importer/issues/895
-	if len(dataVolumeName) > 63 {
-		return nil, fmt.Errorf("dataVolumeName size %v, is bigger than 63 characters", len(dataVolumeName))
+	if len(c.DataVolumeName) > 63 {
+		return nil, fmt.Errorf("dataVolumeName size %v, is bigger than 63 characters", len(c.DataVolumeName))
```
Comment (ahmedwaleedmalik) [inline pkg/cloudprovider/provider/kubevirt/provider.go:538]: I wonder if we really need this check since the name for resources in Kubernetes is already limited to 63 characters. So `machine.name` will never exceed this limit.

File: pkg/cloudprovider/provider/kubevirt/provider.go [hunk 2]
```diff
@@ -101,6 +101,7 @@ type Config struct {
 	PodAffinityPreset     AffinityType
 	PodAntiAffinityPreset AffinityType
 	NodeAffinityPreset    NodeAffinityPreset
+	DataVolumeName        string
```
Comment (mfranczy) [inline pkg/cloudprovider/provider/kubevirt/provider.go:104]: why do we need this `DataVolumeName`? This is too vague.

**Review by mfranczy — CHANGES_REQUESTED** [review]

File: pkg/cloudprovider/provider/kubevirt/provider.go (hunk 2 above)
Comment (mfranczy) [reply pkg/cloudprovider/provider/kubevirt/provider.go:104]: better is to just extend the secondary disks struct with name and add the naming when parse config

Comment (mfranczy) [reply pkg/cloudprovider/provider/kubevirt/provider.go:104]: https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/kubevirt/provider.go#L299-L302

Comment (sankalp-r) [reply pkg/cloudprovider/provider/kubevirt/provider.go:104]: > https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/kubevirt/provider.go#L299-L302

I thought of a similar way, but inside `getConfig`, we don't have access to `machineName`.

**Review by mfranczy — APPROVED** [review]
I think we have to re-work the whole MC KubeVirt provider and add tests for it. I will open a dedicated ticket for this. I am ok to merge that because it's a hot-fix.

/lgtm
/approve

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
