### PR TITLE
vSphere VM cleanup after ISO failure

### LINKED ISSUE #377: Vsphere: Instance does not get cleaned up when ISO generation or attaching fails
Vsphere creates and uploads an ISO file for Ubuntu and CentOS.

If the creation or the upload or the iso fails, we are in a half-created state from which we can not recover. Instead we should cleanup, so another Create will be attempted.

### PR DESCRIPTION
**Pull request by themue**
**What this PR does / why we need it**:

In case `uploadAndAttachISO()` fails the already created VM gets destroyed.

**Which issue(s) this PR fixes**:

Fixes #377 

**Special notes for your reviewer**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/cloudprovider/provider/vsphere/provider.go [hunk 1]
```diff
@@ -385,6 +385,14 @@ func (p *provider) Create(machine *v1alpha1.Machine, _ *cloud.MachineCreateDelet
 		}()
 
 		if err := uploadAndAttachISO(ctx, finder, virtualMachine, localUserdataIsoFilePath, config.Datastore); err != nil {
+			// Destroy VM to avoid a leftover.
+			destroyTask, err := virtualMachine.Destroy(ctx)
+			if err != nil {
+				return nil, fmt.Errorf("failed to destroy vm %s: %v", virtualMachine.Name(), err)
```
Comment (alvaroaleman) [inline pkg/cloudprovider/provider/vsphere/provider.go]: Can you for both possible errors please also add the info that the uploadAndAttachIso failed and the error that happened there?
