### PR TITLE
fix instance deletion for AWS

### LINKED ISSUE #154: Not possible to delete machines using AWS
We have 2 clusters on dev.kubermatic.io which cannot be deleted because the machine-controller is not able to delete the machines.

Logs:
`kubectl -n cluster-dt56ds7tsb logs machine-controller-559788b7f9-89q9v`
```
E0411 07:29:28.561133       1 machine.go:200] machine-kubermatic-dt56ds7tsb-gf4xr failed with: failed to delete machine at cloudprovider, due to instance not found
E0411 07:29:28.594842       1 machine.go:200] machine-kubermatic-dt56ds7tsb-d5pgz failed with: failed to delete machine at cloudprovider, due to instance not found
E0411 07:29:28.613675       1 machine.go:200] machine-kubermatic-dt56ds7tsb-64ql4 failed with: failed to delete machine at cloudprovider, due to instance not found
```

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
Fixes the general deletion logic

Fixes #154

### CODE REVIEW

File: pkg/controller/machine.go [hunk 1]
```diff
@@ -372,49 +372,53 @@ func (c *Controller) syncHandler(key string) error {
...
+		}
 
-	// step 2: check that the instance has really gone
-	if providerInstance, err = c.getProviderInstance(prov, machine); err == nil {
-		if sets.NewString(string(instance.StatusDeleted), string(instance.StatusDeleting)).Has(string(providerInstance.Status())) {
-			glog.V(4).Infof("deletion of instance %s got triggered. Waiting until it fully disappears", providerInstance.ID())
-			c.workqueue.AddAfter(machine.Name, deletionRetryWaitPeriod)
-			return nil
+		// step 1.2 the instance could not be found -> it's gone, so we remove the finalizer. This essentially will remove the machine object from the system
+		glog.V(4).Infof("Deleted machine %s at cloud provider", machine.Name)
```
Comment (alvaroaleman) [inline pkg/controller/machine.go]: Can we try to use max level 3 for our logging because at 4 is the output of the leader election which is extremely verbose?

Comment (mrIncompetent) [reply pkg/controller/machine.go]: 4 is default. I would like to not bend our code for the fact that the leaderelection log level is poorly set

File: pkg/controller/machine.go [hunk 2]
```diff
@@ -372,49 +372,53 @@ func (c *Controller) syncHandler(key string) error {
...
+			return fmt.Errorf("failed to update machine after removing the delete instance finalizer: %v", err)
 		}
-		glog.V(2).Infof("instance %s of machine %s is not deleted yet", providerInstance.ID(), machine.Name)
+
+		glog.V(4).Infof("Removed delete finalizer from machine %s", machine.Name)
+		return nil
+	}
+
+	// step 2: we still have an instance on the cloud provider
+
```
Comment (p0lyn0mial) [inline pkg/controller/machine.go]: nit: remove empty space

File: pkg/controller/machine.go [hunk 3]
```diff
@@ -372,49 +372,53 @@ func (c *Controller) syncHandler(key string) error {
...
-	// step 1: delete provider instance
-	if err = c.deleteProviderInstance(prov, machine); err != nil {
-		message := fmt.Sprintf("%v. Please manually delete finalizers from the machine object.", err)
-		return c.updateMachineErrorIfTerminalError(machine, machinev1alpha1.DeleteMachineError, message, err, "failed to delete machine at cloudprovider")
-	}
+	// step 1: get the provider instance.
+	providerInstance, err := c.getProviderInstance(prov, machine)
+	if err != nil {
+		// step 1.1: failed to get instance, because of some unknown error -> return and see if we need to handle a terminal error here
+		if err != cloudprovidererrors.ErrInstanceNotFound {
```
Comment (p0lyn0mial) [inline pkg/controller/machine.go]: some providers like `DO` detect the `ErrInsanceNotFound` and will return `nil` instead.

https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/digitalocean/provider.go#L350

Comment (mrIncompetent) [reply pkg/controller/machine.go]: I'll update the do code, to return `cloudprovidererrors.ErrInstanceNotFound`
